services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  rag-eval-gtc-2025:
    privileged: true
    network_mode: host
    build:
        context: ..
        dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS CodËœe to mount the folder of your project
      - ..:/rag-eval-gtc-2025

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: [ "/bin/bash" ]
    command: [ "-c", "tail -f /dev/null" ]
